Traceback (most recent call last):
  File "/data/uqhmcdou/HM_Lag_Recovery/LineFit01.py", line 16, in <module>
  File "/data/uqhmcdou/HM_Lag_Recovery/fitting_procedure.py", line 16, in <module>
  File "/home/uqhmcdou/.conda/envs/lag_conda/lib/python3.10/site-packages/jax/__init__.py", line 46, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 975, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
MemoryError
